### ISSUE TITLE
debian

### ISSUE THREAD

**Issue by lxle** [stacefauske/bodhibuilder#5] opened 2018-09-03 06:00 UTC
think you could ever bring this tool to debian?

**Comment by stacefauske** [comment] 2018-11-12 16:48
I currently don't have any plans to bring it to debian. The problem is that I just don't have the time to do a major overhaul like that. But I do agree that it would be nice to have.
I'm going to close this as an issue, but if you have any ideas or know of anyone who would submit some code for testing I would be willing to open this issue again.

**Closed as completed by stacefauske** 2018-11-12 16:48 UTC
